[paths]
dataset = './data'
annotation = './annotation.nrrd'
ontology = './ontology.json'
fus_region_values = './fus_region_values.parquet'
plots = './plots'

[parameters]
voxel_percentile_thresh = 50
voxel_norm_percentile = 99
valid_region_voxel_ratio = 0.8
valid_region_pose_ratio = 0.8
min_sample_n = 5
fus_delay_s = 2.0